### PR TITLE
Accumulate Server Translations

### PR DESCRIPTION
**Pull request by Chaosmeister**
implement #363 

Todo:
- [x] add loaders.
- [ ] move remaining phrases to common.phrases.txt

### CODE REVIEW

**Comment by stickz** [comment]
Delete the entire `nd_sniper_limit` folder in `/updater`. This is no longer used.

**Comment by Chaosmeister** [comment]
sniper limit has been removed.

**Comment by Chaosmeister** [comment]
translationloaders added in structminigame and unit_limit.

**Comment by stickz** [comment]
`structminigame` must use `Consortium` header until next pull request. Modify here.

```
char teamTrans[16];
		switch (team)
		{
			case TEAM_CONSORT: Format(teamTrans, sizeof(teamTrans), "Consort");  
			case TEAM_EMPIRE:  Format(teamTrans, sizeof(teamTrans), "Empire");
		}
```

**Comment by stickz** [comment]
Translation headers in nd_common need to be` "Round Start Usage`" and `"Round End Usage"`, to match the changes to the server printouts. Otherwise, they will not print properly.

**Comment by stickz** [comment]
Use PrintMessage(client, "Translation Phrase") wrapper for `nd_teamdiff/commands.sp`.

Go to `nd_teamdiff_display.sp` make sure nd_print is included. Load common translations OnPluginStart().

**Comment by stickz** [comment]
Remove "You Surrendered" phrase from nd_surrender.phrases.

**Comment by stickz** [comment]
`"You Surrendered"` phrase only committed remove of french translations.

**Comment by Chaosmeister** [comment]
The french translation was the last one, where I missed it, as far as I can see.

**Comment by stickz** [comment]
`nd.ping.sp` Use  PrintMessage(client, "On Team"); instead of reply to command. Other repeats of "invalid team" use too different plugin formatting to accumulate. That can't be changed in this PR.

**Comment by stickz** [comment]
Load nd_common.phrases in nd_universal_translator plugin.

**Comment by stickz** [comment]
Remove `"Please Wait"` from nd_team_balancer.phrases. (This is now for nd_warmup)

**Comment by stickz** [comment]
Pull request is ready for merge after `"Please Wait"` removal, if you don't have anything else to do.

**Comment by stickz** [comment]
PR merged. Create a new PR for any further changes. This is enough things to track at once.

- **To Do:** Update sourcemod translater site

- LoadTranslations("nd_common.phrases"); nd_team_balancer

**Comment by Chaosmeister** [comment]
"Balancer Not Run" and "Balancer Off" are both used in team_balancer and warmup.
Incorrect or another common candidate?

**Comment by stickz** [comment]
Incorrect. Remove from nd_team_balancer. This can be done in anther pull request.

**Pull request merged**
