### PR TITLE
Revert "Simplify Travis CI deployment"

### PR DESCRIPTION
**Pull request by stickz**
Attempt to fix build feature not working.
Reverts stickz/Redstone#59

### CODE REVIEW

**Comment by sergeylukin** [comment]
Yep, I've just noticed that the build is not updated too. However, it wasn't updated since 21 hours ago and this commit was merged 6 hours ago. Any ideas what happened 21 hours ago? Also I don't see errors in Travis. Didn't you change your OAuth token accidentally?

**Comment by stickz** [comment]
Nope, my OAuth token is still there unchanged.

**Comment by stickz** [comment]
Yup, reverting this commit fixed the issue. I merged this before creating anything to build today.

**Comment by sergeylukin** [comment]
I see. Well seems like `GH_TOKEN` environment variable that is encrypted is not available from within `deploy` process in Travis, unfortunately.

**Comment by sergeylukin** [comment]
And there were no errors related to deployment because I silence it with `@` flag in `Makefile` in order to not reveal the real value of `GH_TOKEN` variable.

**Pull request merged**
