### PR TITLE
Automated plugins update

### PR DESCRIPTION
**Pull request by sergeylukin**
In continue to #29 

Fully automated build process. Warning: merging this PR will replace contents of `build` branch and update all plugins.
Please run `make` locally first to verify the contents of `build` directory before merging.

### CODE REVIEW

**Comment by stickz** [comment]
See issue #29. The script shouldn't create directories for plugins which don't have them.
`fatal: Could not switch to '/home/travis/build/stickz/Redstone/updater/dontshout/': No such file or directory`

**Comment by sergeylukin** [comment]
I'm on it. The error is not related to that though.

**Comment by sergeylukin** [comment]
Done. Looks good to me. Please run `make` locally and double check `./build` directory contents.

Note that for Updater I use first 7 characters of hash of most recent git commit that was related to plugin or it's translations.

**Comment by sergeylukin** [comment]
Btw here is live demo of what is generated: https://github.com/sergeylukin/Redstone/tree/build

**Comment by sergeylukin** [comment]
Please let me know how it works out once Updater runs next time and updates all the files.

**Pull request merged**
