### PR TITLE
Translate surrender phrases into russian

### PR DESCRIPTION
**Pull request by sergeylukin**
Brief explanation:

- Fixing "Four Required" phrase (display 4 instead of 8) + rephrase it and similar phrases

- Fix tiny typos like character missing

- Converted encoding. Originally file was encoded with Windows-1251 which is pointless in my opinion as it makes it hard to edit file in environments like using Vim under Unix or any other editor in any other OS that works well with UTF-8 but is not aware of Windows-1251 which is too specific. Please check whether this change doesn't break reading the file on production server, however I doubt it should break anything as UTF-8 is really the most popular encoding out there so if server was fine with Windows-1251 it will eat this new UTF-8 encoded file for breakfast.

Cheers

### CODE REVIEW

**Comment by stickz** [comment]
Thanks!

**Comment by stickz** [comment]
@sergeylukin The phrase "Typed Surrender" is missing from the Russian file. I just added support for that phrase a few days ago. The most important phrase still isn't translated. :(
https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/nd_surrender.phrases.txt

**Comment by sergeylukin** [comment]
NP. Translated "Typed Surrender" in https://github.com/stickz/Redstone/pull/32

**Comment by stickz** [comment]
Thanks!

**Pull request merged**
