### PR TITLE
improve translation consistency

### PR DESCRIPTION
**Pull request by Chaosmeister**
* remove a lot of punctuation, whitespaces.
* remove duplicate entry in nd_disconnect.phrases.txt:
```
"Lost Connection"
{
    "de"        "Verbindung von {1} abgebrochen"
 }
```

### CODE REVIEW

**Comment by stickz** [comment]
Punctuation needs hard-coded in the [mapchooser](https://github.com/stickz/Redstone/blob/master/addons/sourcemod/scripting/mapchooser.sp) plugin.

**Comment by stickz** [comment]
This is a mess there's punctuation all over the place. Just remove it all from the end of translation files. Missing punctuation can be re-added once all the plugins use better translation wrappers.

I meant to add punctuation into plugins missing  without wrappers, but lacked clarity.

**Comment by Chaosmeister** [comment]
Really every message? that can be automated pretty well

**Comment by stickz** [comment]
> Really every message? that can be automated pretty well
That is what i'm saying. All punctuation on the end of sentences should be automated.

**Pull request closed without merging**
